import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BookOpen, Download, Eye, FileText, Trophy, Upload } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { fetchDashboard, getCachedDashboard, type DashboardData, type ResourceSummary } from '../lib/client';
import { authApi } from '../lib/auth';
import { useAuth } from '../contexts/AuthContext';

function ResourceCard({ resource }: { resource: ResourceSummary }) {
  const navigate = useNavigate();
  const book = resource.type === 'book';
  const meta = resource.metadata;
  const courses = book ? (meta.courses || []).map((c: any) => c.code || c.name).join(' · ') : `${meta.course_code || 'Course unavailable'} · ${meta.year || '—'} · ${meta.paper_type || 'Paper'}`;
  return <div className="theme-list-row flex items-center gap-4 rounded-lg p-4"><div className="theme-accent-soft flex h-12 w-12 shrink-0 items-center justify-center rounded-lg">{book ? <BookOpen className="theme-section-icon h-6 w-6" /> : <FileText className="theme-section-icon h-6 w-6" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{book ? 'BOOK' : 'PAPER'}</Badge><h3 className="theme-title truncate font-medium">{resource.title}</h3></div><p className="theme-muted mt-1 text-sm">{book ? (meta.authors || []).join(', ') || 'Author not specified' : courses}</p>{book && <p className="theme-muted mt-1 text-xs">{courses || 'No related course'}{meta.modules?.length ? ` · ${meta.modules.map((m: any) => m.code || m.name).join(' · ')}` : ''}</p>}<div className="mt-2 flex flex-wrap gap-2 text-xs">{book ? <Badge variant="secondary">{resource.visibility} · {meta.status}</Badge> : <Badge variant="secondary">{resource.verification_status || 'unverified'}</Badge>}{book && meta.file_name && <span className="theme-muted">{meta.file_name}</span>}</div></div><span className="theme-muted flex items-center gap-1 text-xs"><Download className="h-3.5 w-3.5" />{resource.downloads}</span><Button variant="ghost" size="icon" className="theme-ghost-brand-button" onClick={() => navigate(book ? `/book/${resource.id}` : `/paper/${resource.id}`)}><Eye className="h-4 w-4" /></Button></div>;
}

export default function DashboardPage() {
  const navigate = useNavigate(); const { user, loading: authLoading } = useAuth();
  const [dashboard, setDashboard] = useState<DashboardData | null>(() => getCachedDashboard());
  const [loading, setLoading] = useState(!dashboard);
  useEffect(() => { if (!user) return; let active = true; const refresh = async () => { try { const next = await fetchDashboard(); if (active) setDashboard(next); } finally { if (active) setLoading(false); } }; void refresh(); window.addEventListener('ur-resource-mutated', refresh); return () => { active = false; window.removeEventListener('ur-resource-mutated', refresh); }; }, [user]);
  if (authLoading) return <div className="flex min-h-screen items-center justify-center"><div className="theme-spinner h-8 w-8 animate-spin rounded-full border-b-2 border-current" /></div>;
  if (!user) return <div className="mx-auto max-w-2xl px-4 py-16 text-center"><h2 className="theme-title text-2xl font-bold">Sign In Required</h2><Button className="theme-accent-bg mt-6" onClick={() => authApi.login('/dashboard')}>Sign In</Button></div>;
  const stats = dashboard?.stats; const resources = dashboard?.uploaded_resources || [];
  const cards = [[stats?.total_uploads, 'My Uploads', FileText], [stats?.book_count, 'Books', BookOpen], [stats?.total_downloads, 'Total Downloads', Download], [stats?.verified_paper_count, 'Verified Papers', Trophy]] as const;
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="theme-title text-3xl font-bold">My Dashboard</h1><p className="theme-muted mt-1">Your academic-resource activity</p></div><Button className="theme-accent-bg" onClick={() => navigate('/upload')}><Upload className="mr-2 h-4 w-4" />Upload Resource</Button></div><div className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([value, label, Icon]) => <Card key={label} className="theme-panel"><CardContent className="flex items-center gap-4 p-4"><div className="theme-accent-soft flex h-12 w-12 items-center justify-center rounded-lg"><Icon className="theme-section-icon h-6 w-6" /></div><div><p className="theme-title text-2xl font-bold">{value ?? 0}</p><p className="theme-muted text-sm">{label}</p></div></CardContent></Card>)}</div><div className="mb-8 grid gap-4 lg:grid-cols-2"><Card className="theme-panel"><CardHeader><CardTitle className="theme-title">Contributor Status</CardTitle></CardHeader><CardContent className="theme-muted space-y-2 text-sm"><p>Role: <span className="font-semibold">{dashboard?.contribution.role || user.role}</span></p><p>Contribution score: <span className="font-semibold">{dashboard?.contribution.trust_score || 0}</span></p><p>Upload count: <span className="font-semibold">{dashboard?.contribution.upload_count ?? stats?.total_uploads ?? 0}</span></p><p>Resources: <span className="font-semibold">{stats?.paper_count || 0} papers · {stats?.book_count || 0} books</span></p></CardContent></Card><Card className="theme-panel"><CardHeader><CardTitle className="theme-title">Leaderboard</CardTitle></CardHeader><CardContent className="space-y-3">{(dashboard?.leaderboard || []).slice(0, 5).map((entry, index) => <div key={entry.id} className="theme-list-row flex justify-between rounded-lg p-3"><span>{index + 1}. {entry.display_name}</span><Badge variant="secondary">{entry.trust_score || 0} pts</Badge></div>)}</CardContent></Card></div><Card className="theme-panel"><CardHeader><CardTitle className="theme-title">My Uploaded Resources</CardTitle></CardHeader><CardContent className="space-y-3">{loading && !dashboard ? <p className="theme-muted">Loading your resources…</p> : resources.length ? resources.map((item) => <ResourceCard key={`${item.type}-${item.id}`} resource={item} />) : <div className="py-10 text-center"><p className="theme-muted">No uploads yet. Start by sharing a paper or book.</p><Button className="theme-accent-bg mt-4" onClick={() => navigate('/upload')}>Upload Resource</Button></div>}</CardContent></Card></div>;
}
